/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [1-1:0] M_edge_dt_btn_1_out;
  reg [1-1:0] M_edge_dt_btn_1_in;
  edge_detector_2 edge_dt_btn_1 (
    .clk(clk),
    .in(M_edge_dt_btn_1_in),
    .out(M_edge_dt_btn_1_out)
  );
  wire [1-1:0] M_edge_dt_btn_2_out;
  reg [1-1:0] M_edge_dt_btn_2_in;
  edge_detector_2 edge_dt_btn_2 (
    .clk(clk),
    .in(M_edge_dt_btn_2_in),
    .out(M_edge_dt_btn_2_out)
  );
  wire [1-1:0] M_btn_cond_1_out;
  reg [1-1:0] M_btn_cond_1_in;
  button_conditioner_4 btn_cond_1 (
    .clk(clk),
    .in(M_btn_cond_1_in),
    .out(M_btn_cond_1_out)
  );
  wire [1-1:0] M_btn_cond_2_out;
  reg [1-1:0] M_btn_cond_2_in;
  button_conditioner_4 btn_cond_2 (
    .clk(clk),
    .in(M_btn_cond_2_in),
    .out(M_btn_cond_2_out)
  );
  wire [6-1:0] M_game_FSM_alufn;
  wire [3-1:0] M_game_FSM_asel;
  wire [3-1:0] M_game_FSM_bsel;
  wire [2-1:0] M_game_FSM_demux;
  wire [8-1:0] M_game_FSM_led_out;
  wire [8-1:0] M_game_FSM_led_out_1;
  wire [8-1:0] M_game_FSM_led_out_2;
  reg [1-1:0] M_game_FSM_enter;
  reg [1-1:0] M_game_FSM_toggle;
  game_FSM_6 game_FSM (
    .clk(clk),
    .rst(rst),
    .enter(M_game_FSM_enter),
    .toggle(M_game_FSM_toggle),
    .alufn(M_game_FSM_alufn),
    .asel(M_game_FSM_asel),
    .bsel(M_game_FSM_bsel),
    .demux(M_game_FSM_demux),
    .led_out(M_game_FSM_led_out),
    .led_out_1(M_game_FSM_led_out_1),
    .led_out_2(M_game_FSM_led_out_2)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    io_led[0+7-:8] = M_game_FSM_led_out;
    io_led[8+7-:8] = M_game_FSM_led_out_1;
    io_led[16+7-:8] = M_game_FSM_led_out_2;
    M_btn_cond_1_in = io_button[1+0-:1];
    M_btn_cond_2_in = io_button[4+0-:1];
    M_edge_dt_btn_1_in = M_btn_cond_1_out;
    M_edge_dt_btn_2_in = M_btn_cond_2_out;
    M_game_FSM_enter = M_edge_dt_btn_1_out;
    M_game_FSM_toggle = M_edge_dt_btn_2_out;
  end
endmodule
